import sys
import os
import subprocess
import json
import time
import threading
import socket
from datetime import datetime

# ==============================================================================
# Executable & CustomTkinter Asset Path Patch (for Frozen Executables)
# ==============================================================================
if getattr(sys, 'frozen', False):
    import builtins
    _orig_open = builtins.open
    def _custom_open(file, *args, **kwargs):
        try:
            file_str = os.fspath(file) if isinstance(file, (str, bytes, os.PathLike)) else str(file)
            if "customtkinter" in file_str and (".exe" in file_str or ".zip" in file_str):
                exe_dir = os.path.dirname(sys.executable)
                idx = file_str.find("customtkinter")
                if idx != -1:
                    file = os.path.join(exe_dir, file_str[idx:])
        except Exception:
            pass
        return _orig_open(file, *args, **kwargs)
    builtins.open = _custom_open

# ==============================================================================
# Auto-Install Missing Dependencies (Skipped when running as frozen .exe)
# ==============================================================================
REQUIRED_PACKAGES = [
    "pyserial",
    "cryptography",
    "paramiko",
    "customtkinter",
    "pycryptodome",
    "pillow"
]

def auto_install_dependencies():
    if getattr(sys, 'frozen', False):
        return

    missing = []
    for pkg in REQUIRED_PACKAGES:
        try:
            if pkg == "pyserial":
                __import__("serial")
            elif pkg == "pycryptodome":
                __import__("Crypto")
            elif pkg == "pillow":
                __import__("PIL")
            else:
                __import__(pkg)
        except ImportError:
            missing.append(pkg)

    if missing:
        print(f"Installing missing dependencies: {missing}...")
        try:
            subprocess.run([sys.executable, "-m", "pip", "install"] + missing, check=True)
            print("Dependencies installed successfully!")
        except Exception as e:
            print(f"Warning: Failed auto-installing dependencies: {e}")

auto_install_dependencies()

# Standard Library & Third-Party Imports
import serial
import serial.tools.list_ports
import customtkinter as ctk
from tkinter import messagebox, filedialog
from Crypto.Cipher import AES

# Set CustomTkinter Appearance
ctk.set_appearance_mode("light")
ctk.set_default_color_theme("blue")

# ==============================================================================
# Constants & Cryptographic Configuration
# ==============================================================================
AES_KEY = b'MySecr3tAESKey!!'  # 16 bytes matching ESP32
AES_IV  = bytes(range(16))     # 0x00..0x0F matching ESP32
TARGET_DIR = r"C:\tmp"
SCP_PORT = 2222

os.makedirs(TARGET_DIR, exist_ok=True)

def decrypt_aes128_hex(hex_str):
    """Decrypts AES-128-CBC hex payload generated by ESP32."""
    try:
        cipher_bytes = bytes.fromhex(hex_str.strip())
        cipher = AES.new(AES_KEY, AES.MODE_CBC, AES_IV)
        decrypted = cipher.decrypt(cipher_bytes)
        # Remove PKCS7 padding
        pad_len = decrypted[-1]
        if pad_len <= 16:
            decrypted = decrypted[:-pad_len]
        return decrypted.decode('utf-8', errors='ignore')
    except Exception as e:
        return f"Decryption Error: {e}"

from http.server import HTTPServer, BaseHTTPRequestHandler

# ==============================================================================
# Embedded HTTP POST File Receiver Server
# ==============================================================================
class HTTPAuthPostReceiver:
    def __init__(self, callback_file_received):
        self.callback = callback_file_received
        self.running = True

        self.t1 = threading.Thread(target=self._run_http_server, args=(5000,), daemon=True)
        self.t2 = threading.Thread(target=self._run_http_server, args=(2222,), daemon=True)

    def start(self):
        self.t1.start()
        self.t2.start()

    def _save_and_notify(self, filename, hex_content, client_ip, method):
        filepath = os.path.join(TARGET_DIR, filename)
        try:
            with open(filepath, "w") as f:
                f.write(hex_content)
            print(f"[{method}] Received {filename} from {client_ip}")
            if self.callback:
                self.callback(filename, hex_content, client_ip)
        except Exception as e:
            print(f"Error saving auth file from {method}: {e}")

    def _run_http_server(self, port):
        callback_ref = self._save_and_notify

        class RequestHandler(BaseHTTPRequestHandler):
            def do_POST(self):
                try:
                    length = int(self.headers.get('Content-Length', 0))
                    body = self.rfile.read(length).decode('utf-8', errors='ignore')
                    
                    filename = "auth_status.enc"
                    hex_content = ""
                    
                    try:
                        data = json.loads(body)
                        filename = data.get("filename", "auth_status.enc")
                        hex_content = data.get("data", "")
                    except Exception:
                        hex_content = body.strip()

                    if "success" in filename.lower():
                        filename = "auth_success.enc"
                    elif "false" in filename.lower():
                        filename = "auth_false.enc"

                    callback_ref(filename, hex_content, self.client_address[0], f"HTTP POST Port {port}")

                    self.send_response(200)
                    self.send_header('Content-Type', 'application/json')
                    self.end_headers()
                    self.wfile.write(b'{"status":"success"}')
                except Exception as e:
                    self.send_response(500)
                    self.end_headers()

            def log_message(self, format, *args):
                pass

        try:
            httpd = HTTPServer(('0.0.0.0', port), RequestHandler)
            httpd.serve_forever()
        except Exception as e:
            print(f"HTTP Server port {port} error: {e}")

# ==============================================================================
# Main Application GUI
# ==============================================================================
class OSLoaderApp(ctk.CTk):
    def __init__(self):
        super().__init__()

        self.title("OSLoader - ESP32 Fingerprint Control & Auth Center")
        self.geometry("1180x780")
        self.minsize(1000, 680)

        # State Variables
        self.is_authenticated = False
        self.serial_conn = None
        self.serial_thread = None
        self.heartbeat_thread = None
        self.serial_running = False
        self.selected_port = ""
        self.login_history = []
        self.enrolled_templates = []
        self.connected_stations = []

        # Colors System (Light Modern Theme)
        self.COLORS = {
            "bg": "#F8F9FA",
            "card": "#FFFFFF",
            "border": "#E2E8F0",
            "primary": "#2563EB",
            "primary_hover": "#1D4ED8",
            "success": "#16A34A",
            "success_bg": "#DCFCE7",
            "danger": "#DC2626",
            "danger_bg": "#FEE2E2",
            "text_dark": "#0F172A",
            "text_muted": "#64748B"
        }

        self.configure(fg_color=self.COLORS["bg"])

        # Start HTTP POST Auth File Server Daemon (Ports 5000 & 2222)
        self.http_server = HTTPAuthPostReceiver(self.on_scp_file_received)
        self.http_server.start()

        # Build UI Sections
        self.build_lock_screen()
        self.build_main_dashboard()

        # Show Lock Screen Initially
        self.show_lock_screen()

    # --------------------------------------------------------------------------
    # Lock Screen Layout
    # --------------------------------------------------------------------------
    def build_lock_screen(self):
        self.lock_frame = ctk.CTkFrame(self, fg_color=self.COLORS["bg"])

        # Center Card
        card = ctk.CTkFrame(
            self.lock_frame,
            fg_color=self.COLORS["card"],
            corner_radius=20,
            border_width=1,
            border_color=self.COLORS["border"],
            width=540,
            height=580
        )
        card.place(relx=0.5, rely=0.5, anchor="center")

        # Icon Badge
        self.lock_icon_label = ctk.CTkLabel(
            card,
            text="🔒",
            font=("Segoe UI Emoji", 72)
        )
        self.lock_icon_label.pack(pady=(35, 10))

        # Title
        ctk.CTkLabel(
            card,
            text="OSLoader Security Console",
            font=("Segoe UI", 24, "bold"),
            text_color=self.COLORS["text_dark"]
        ).pack(pady=(0, 5))

        ctk.CTkLabel(
            card,
            text="Fingerprint Verification Required to Unlock",
            font=("Segoe UI", 13),
            text_color=self.COLORS["text_muted"]
        ).pack(pady=(0, 20))

        # Status Pill Box
        self.lock_status_box = ctk.CTkFrame(
            card,
            fg_color=self.COLORS["bg"],
            corner_radius=12,
            border_width=1,
            border_color=self.COLORS["border"]
        )
        self.lock_status_box.pack(fill="x", padx=40, pady=10)

        self.lock_status_label = ctk.CTkLabel(
            self.lock_status_box,
            text="● Disconnected from ESP32 Serial",
            font=("Segoe UI", 13, "bold"),
            text_color=self.COLORS["danger"]
        )
        self.lock_status_label.pack(pady=12)

        # Serial Connection Control
        serial_bar = ctk.CTkFrame(card, fg_color="transparent")
        serial_bar.pack(fill="x", padx=40, pady=15)

        self.port_combo = ctk.CTkComboBox(
            serial_bar,
            values=self.get_serial_ports(),
            font=("Segoe UI", 12),
            width=180
        )
        self.port_combo.pack(side="left", padx=(0, 10))

        self.btn_refresh_ports = ctk.CTkButton(
            serial_bar,
            text="🔄",
            width=40,
            fg_color=self.COLORS["bg"],
            text_color=self.COLORS["text_dark"],
            hover_color=self.COLORS["border"],
            command=self.refresh_serial_ports
        )
        self.btn_refresh_ports.pack(side="left", padx=(0, 10))

        self.btn_connect = ctk.CTkButton(
            serial_bar,
            text="Connect ESP32",
            font=("Segoe UI", 12, "bold"),
            fg_color=self.COLORS["primary"],
            hover_color=self.COLORS["primary_hover"],
            command=self.toggle_serial_connection
        )
        self.btn_connect.pack(side="left", fill="x", expand=True)

        # Prompt Info
        ctk.CTkLabel(
            card,
            text="Touch finger on ESP32 sensor. Valid scan unlocks GUI & sends SCP auth file to C:\\tmp.",
            font=("Segoe UI", 11),
            text_color=self.COLORS["text_muted"],
            wraplength=420
        ).pack(pady=15)

        # Admin Emergency Unlock Button
        ctk.CTkButton(
            card,
            text="Emergency Admin Key 🔑",
            font=("Segoe UI", 11),
            fg_color="transparent",
            text_color=self.COLORS["text_muted"],
            hover_color=self.COLORS["bg"],
            command=self.admin_bypass_prompt
        ).pack(pady=(0, 20))

    # --------------------------------------------------------------------------
    # Main Unlocked Dashboard Layout
    # --------------------------------------------------------------------------
    def build_main_dashboard(self):
        self.main_frame = ctk.CTkFrame(self, fg_color=self.COLORS["bg"])

        # Top Header Bar (With Generous Margins & No Overlap)
        header = ctk.CTkFrame(
            self.main_frame,
            fg_color=self.COLORS["card"],
            corner_radius=12,
            border_width=1,
            border_color=self.COLORS["border"],
            height=70
        )
        header.pack(fill="x", side="top", padx=20, pady=(15, 10))

        # Title Label on Left
        ctk.CTkLabel(
            header,
            text="🛡️ OSLoader Fingerprint Control Center",
            font=("Segoe UI", 18, "bold"),
            text_color=self.COLORS["text_dark"]
        ).pack(side="left", padx=20, pady=15)

        # Action Buttons on Right
        btn_lock = ctk.CTkButton(
            header,
            text="Lock GUI 🔒",
            font=("Segoe UI", 12, "bold"),
            fg_color=self.COLORS["danger_bg"],
            text_color=self.COLORS["danger"],
            hover_color="#FCA5A5",
            width=110,
            height=36,
            command=self.show_lock_screen
        )
        btn_lock.pack(side="right", padx=15, pady=12)

        self.ap_badge = ctk.CTkLabel(
            header,
            text="📡 ESP32 AP: 192.168.4.1 (0 Connected)",
            font=("Segoe UI", 12, "bold"),
            fg_color=self.COLORS["success_bg"],
            text_color=self.COLORS["success"],
            corner_radius=8,
            padx=12,
            pady=6
        )
        self.ap_badge.pack(side="right", padx=10, pady=12)

        # Main Tabview Container
        self.tabview = ctk.CTkTabview(
            self.main_frame,
            fg_color=self.COLORS["card"],
            segmented_button_fg_color=self.COLORS["bg"],
            segmented_button_selected_color=self.COLORS["primary"],
            segmented_button_selected_hover_color=self.COLORS["primary_hover"],
            corner_radius=16
        )
        self.tabview.pack(fill="both", expand=True, padx=20, pady=(5, 15))

        # Tabs Setup
        self.tab_enroll = self.tabview.add("👆 Enroll Fingerprint")
        self.tab_users = self.tabview.add("👤 Enrolled Users")
        self.tab_devices = self.tabview.add("📡 Hotspot Devices")
        self.tab_login_log = self.tabview.add("📋 User Login Log")
        self.tab_scp = self.tabview.add("📂 SCP Files (C:\\tmp)")
        self.tab_log = self.tabview.add("⚡ Telemetry Logs")

        self.setup_enroll_tab()
        self.setup_users_tab()
        self.setup_devices_tab()
        self.setup_login_log_tab()
        self.setup_scp_tab()
        self.setup_log_tab()

    # --------------------------------------------------------------------------
    # Tab 1: Enroll Fingerprint
    # --------------------------------------------------------------------------
    def setup_enroll_tab(self):
        container = ctk.CTkFrame(self.tab_enroll, fg_color="transparent")
        container.pack(fill="both", expand=True, padx=20, pady=20)

        # Left Column: Input Form
        form_card = ctk.CTkFrame(
            container,
            fg_color=self.COLORS["card"],
            border_width=1,
            border_color=self.COLORS["border"],
            corner_radius=16,
            width=380
        )
        form_card.pack(side="left", fill="y", padx=(0, 20), pady=10)

        ctk.CTkLabel(
            form_card,
            text="Register New Template",
            font=("Segoe UI", 16, "bold"),
            text_color=self.COLORS["text_dark"]
        ).pack(anchor="w", padx=25, pady=(25, 15))

        # ID Input
        ctk.CTkLabel(form_card, text="Fingerprint ID (1 - 127):", font=("Segoe UI", 12), text_color=self.COLORS["text_muted"]).pack(anchor="w", padx=25, pady=(5, 2))
        self.entry_id = ctk.CTkEntry(form_card, placeholder_text="e.g. 1", font=("Segoe UI", 13))
        self.entry_id.pack(fill="x", padx=25, pady=(0, 15))

        # Name Input
        ctk.CTkLabel(form_card, text="User Full Name:", font=("Segoe UI", 12), text_color=self.COLORS["text_muted"]).pack(anchor="w", padx=25, pady=(5, 2))
        self.entry_name = ctk.CTkEntry(form_card, placeholder_text="e.g. John Doe", font=("Segoe UI", 13))
        self.entry_name.pack(fill="x", padx=25, pady=(0, 20))

        # Submit Button
        self.btn_enroll = ctk.CTkButton(
            form_card,
            text="Start Fingerprint Enrollment 👆",
            font=("Segoe UI", 13, "bold"),
            fg_color=self.COLORS["primary"],
            hover_color=self.COLORS["primary_hover"],
            height=40,
            command=self.start_enrollment
        )
        self.btn_enroll.pack(fill="x", padx=25, pady=(0, 25))

        # Right Column: Interactive Step Card
        self.enroll_wizard = ctk.CTkFrame(
            container,
            fg_color=self.COLORS["card"],
            border_width=1,
            border_color=self.COLORS["border"],
            corner_radius=16
        )
        self.enroll_wizard.pack(side="left", fill="both", expand=True, pady=10)

        ctk.CTkLabel(
            self.enroll_wizard,
            text="Enrollment Interactive Wizard",
            font=("Segoe UI", 16, "bold"),
            text_color=self.COLORS["text_dark"]
        ).pack(anchor="w", padx=25, pady=(25, 10))

        self.enroll_step_icon = ctk.CTkLabel(
            self.enroll_wizard,
            text="👆",
            font=("Segoe UI Emoji", 64)
        )
        self.enroll_step_icon.pack(pady=(20, 10))

        self.enroll_step_title = ctk.CTkLabel(
            self.enroll_wizard,
            text="Ready to Enroll",
            font=("Segoe UI", 18, "bold"),
            text_color=self.COLORS["text_dark"]
        )
        self.enroll_step_title.pack(pady=(0, 5))

        self.enroll_step_msg = ctk.CTkLabel(
            self.enroll_wizard,
            text="Enter ID and Name on the left, then click 'Start Fingerprint Enrollment'.",
            font=("Segoe UI", 13),
            text_color=self.COLORS["text_muted"],
            wraplength=400
        )
        self.enroll_step_msg.pack(pady=(0, 25))

    # --------------------------------------------------------------------------
    # Tab 2: Users Management
    # --------------------------------------------------------------------------
    def setup_users_tab(self):
        container = ctk.CTkFrame(self.tab_users, fg_color="transparent")
        container.pack(fill="both", expand=True, padx=20, pady=20)

        top_bar = ctk.CTkFrame(container, fg_color="transparent")
        top_bar.pack(fill="x", pady=(0, 15))

        ctk.CTkLabel(
            top_bar,
            text="Enrolled Fingerprint Templates in ESP32 Flash",
            font=("Segoe UI", 16, "bold"),
            text_color=self.COLORS["text_dark"]
        ).pack(side="left")

        ctk.CTkButton(
            top_bar,
            text="Refresh List 🔄",
            font=("Segoe UI", 12, "bold"),
            fg_color=self.COLORS["primary"],
            hover_color=self.COLORS["primary_hover"],
            width=130,
            command=self.refresh_templates
        ).pack(side="right")

        # Scrollable Users Table Container
        self.users_scroll = ctk.CTkScrollableFrame(
            container,
            fg_color=self.COLORS["card"],
            border_width=1,
            border_color=self.COLORS["border"],
            corner_radius=16
        )
        self.users_scroll.pack(fill="both", expand=True)

        self.render_user_list([])

    def render_user_list(self, templates):
        self.enrolled_templates = templates
        for child in self.users_scroll.winfo_children():
            child.destroy()

        # Table Header
        header = ctk.CTkFrame(self.users_scroll, fg_color=self.COLORS["bg"], height=40)
        header.pack(fill="x", padx=15, pady=5)

        ctk.CTkLabel(header, text="ID", font=("Segoe UI", 12, "bold"), width=80, anchor="w").pack(side="left", padx=10)
        ctk.CTkLabel(header, text="User Name", font=("Segoe UI", 12, "bold"), anchor="w").pack(side="left", fill="x", expand=True, padx=10)
        ctk.CTkLabel(header, text="Action", font=("Segoe UI", 12, "bold"), width=100, anchor="e").pack(side="right", padx=10)

        if not templates:
            ctk.CTkLabel(
                self.users_scroll,
                text="No templates loaded. Click 'Refresh List 🔄' to sync with ESP32.",
                font=("Segoe UI", 13),
                text_color=self.COLORS["text_muted"]
            ).pack(pady=40)
            return

        for item in templates:
            uid = item.get("id", 0)
            uname = item.get("name", "Unknown")

            row = ctk.CTkFrame(self.users_scroll, fg_color=self.COLORS["card"], height=45)
            row.pack(fill="x", padx=15, pady=4)

            ctk.CTkLabel(row, text=f"#{uid}", font=("Segoe UI", 13, "bold"), width=80, anchor="w", text_color=self.COLORS["primary"]).pack(side="left", padx=10)
            ctk.CTkLabel(row, text=uname, font=("Segoe UI", 13), anchor="w", text_color=self.COLORS["text_dark"]).pack(side="left", fill="x", expand=True, padx=10)

            btn_del = ctk.CTkButton(
                row,
                text="Delete 🗑️",
                font=("Segoe UI", 11, "bold"),
                fg_color=self.COLORS["danger_bg"],
                text_color=self.COLORS["danger"],
                hover_color="#FCA5A5",
                width=80,
                command=lambda id_num=uid: self.delete_template(id_num)
            )
            btn_del.pack(side="right", padx=10)

    # --------------------------------------------------------------------------
    # Tab 3: Connected Hotspot Devices
    # --------------------------------------------------------------------------
    def setup_devices_tab(self):
        container = ctk.CTkFrame(self.tab_devices, fg_color="transparent")
        container.pack(fill="both", expand=True, padx=20, pady=20)

        top_bar = ctk.CTkFrame(container, fg_color="transparent")
        top_bar.pack(fill="x", pady=(0, 15))

        ctk.CTkLabel(
            top_bar,
            text="Devices Connected to ESP32 Wi-Fi Hotspot (192.168.4.1)",
            font=("Segoe UI", 16, "bold"),
            text_color=self.COLORS["text_dark"]
        ).pack(side="left")

        ctk.CTkButton(
            top_bar,
            text="Refresh Devices 🔄",
            font=("Segoe UI", 12, "bold"),
            fg_color=self.COLORS["primary"],
            hover_color=self.COLORS["primary_hover"],
            width=140,
            command=lambda: self.send_serial_cmd("ping")
        ).pack(side="right")

        # Scrollable Devices Table Container
        self.devices_scroll = ctk.CTkScrollableFrame(
            container,
            fg_color=self.COLORS["card"],
            border_width=1,
            border_color=self.COLORS["border"],
            corner_radius=16
        )
        self.devices_scroll.pack(fill="both", expand=True)

        self.render_connected_devices_table([])

    def render_connected_devices_table(self, stations):
        self.connected_stations = stations
        for child in self.devices_scroll.winfo_children():
            child.destroy()

        # Table Header
        header = ctk.CTkFrame(self.devices_scroll, fg_color=self.COLORS["bg"], height=40)
        header.pack(fill="x", padx=15, pady=5)

        ctk.CTkLabel(header, text="Station IP Address", font=("Segoe UI", 11, "bold"), width=160, anchor="w").pack(side="left", padx=10)
        ctk.CTkLabel(header, text="MAC Address", font=("Segoe UI", 11, "bold"), width=180, anchor="w").pack(side="left", padx=10)
        ctk.CTkLabel(header, text="Hotspot Connection Status", font=("Segoe UI", 11, "bold"), anchor="w").pack(side="left", fill="x", expand=True, padx=10)
        ctk.CTkLabel(header, text="SCP Auth Target", font=("Segoe UI", 11, "bold"), width=150, anchor="e").pack(side="right", padx=10)

        if not stations:
            ctk.CTkLabel(
                self.devices_scroll,
                text="No active client devices connected to ESP32 Wi-Fi Hotspot yet.",
                font=("Segoe UI", 13),
                text_color=self.COLORS["text_muted"]
            ).pack(pady=40)
            return

        for sta in stations:
            ip = sta.get("ip", "0.0.0.0")
            mac = sta.get("mac", "00:00:00:00:00:00")

            row = ctk.CTkFrame(self.devices_scroll, fg_color=self.COLORS["card"], height=45)
            row.pack(fill="x", padx=15, pady=4)

            ctk.CTkLabel(row, text=ip, font=("Consolas", 12, "bold"), width=160, anchor="w", text_color=self.COLORS["primary"]).pack(side="left", padx=10)
            ctk.CTkLabel(row, text=mac, font=("Consolas", 11), width=180, anchor="w", text_color=self.COLORS["text_dark"]).pack(side="left", padx=10)

            # Status Badge
            badge = ctk.CTkLabel(
                row,
                text="🟢 ACTIVE / CONNECTED",
                font=("Segoe UI", 10, "bold"),
                fg_color=self.COLORS["success_bg"],
                text_color=self.COLORS["success"],
                corner_radius=6,
                width=160,
                pady=3
            )
            badge.pack(side="left", padx=10)

            ctk.CTkLabel(row, text="SCP Ready (Port 2222/22)", font=("Segoe UI", 11), width=150, anchor="e", text_color=self.COLORS["text_muted"]).pack(side="right", padx=10)

    # --------------------------------------------------------------------------
    # Tab 4: User Login Log History
    # --------------------------------------------------------------------------
    def setup_login_log_tab(self):
        container = ctk.CTkFrame(self.tab_login_log, fg_color="transparent")
        container.pack(fill="both", expand=True, padx=20, pady=20)

        top_bar = ctk.CTkFrame(container, fg_color="transparent")
        top_bar.pack(fill="x", pady=(0, 15))

        ctk.CTkLabel(
            top_bar,
            text="User Verification & Access History Log",
            font=("Segoe UI", 16, "bold"),
            text_color=self.COLORS["text_dark"]
        ).pack(side="left")

        ctk.CTkButton(
            top_bar,
            text="Export Log CSV 📥",
            font=("Segoe UI", 12, "bold"),
            fg_color=self.COLORS["bg"],
            text_color=self.COLORS["text_dark"],
            hover_color=self.COLORS["border"],
            width=130,
            command=self.export_login_log_csv
        ).pack(side="right", padx=(10, 0))

        ctk.CTkButton(
            top_bar,
            text="Clear Logs 🗑️",
            font=("Segoe UI", 12, "bold"),
            fg_color=self.COLORS["danger_bg"],
            text_color=self.COLORS["danger"],
            hover_color="#FCA5A5",
            width=110,
            command=self.clear_login_logs
        ).pack(side="right")

        # Scrollable Table Container
        self.login_scroll = ctk.CTkScrollableFrame(
            container,
            fg_color=self.COLORS["card"],
            border_width=1,
            border_color=self.COLORS["border"],
            corner_radius=16
        )
        self.login_scroll.pack(fill="both", expand=True)

        self.render_login_log_table()

    def add_login_log_entry(self, user_id, name, status, confidence, filename):
        record = {
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "user_id": user_id,
            "name": name,
            "status": status,
            "confidence": confidence,
            "file": filename
        }
        self.login_history.insert(0, record)
        self.render_login_log_table()

    def render_login_log_table(self):
        for child in self.login_scroll.winfo_children():
            child.destroy()

        # Table Header
        header = ctk.CTkFrame(self.login_scroll, fg_color=self.COLORS["bg"], height=40)
        header.pack(fill="x", padx=15, pady=5)

        ctk.CTkLabel(header, text="Timestamp", font=("Segoe UI", 11, "bold"), width=150, anchor="w").pack(side="left", padx=10)
        ctk.CTkLabel(header, text="ID", font=("Segoe UI", 11, "bold"), width=60, anchor="w").pack(side="left", padx=5)
        ctk.CTkLabel(header, text="User Name", font=("Segoe UI", 11, "bold"), anchor="w").pack(side="left", fill="x", expand=True, padx=10)
        ctk.CTkLabel(header, text="Auth Status", font=("Segoe UI", 11, "bold"), width=140, anchor="center").pack(side="left", padx=10)
        ctk.CTkLabel(header, text="Auth File", font=("Segoe UI", 11, "bold"), width=150, anchor="e").pack(side="right", padx=10)

        if not self.login_history:
            ctk.CTkLabel(
                self.login_scroll,
                text="No verification activity recorded yet.",
                font=("Segoe UI", 13),
                text_color=self.COLORS["text_muted"]
            ).pack(pady=40)
            return

        for record in self.login_history:
            row = ctk.CTkFrame(self.login_scroll, fg_color=self.COLORS["card"], height=42)
            row.pack(fill="x", padx=15, pady=4)

            is_success = record["status"] == "SUCCESS"

            ctk.CTkLabel(row, text=record["timestamp"], font=("Segoe UI", 11), width=150, anchor="w", text_color=self.COLORS["text_muted"]).pack(side="left", padx=10)
            ctk.CTkLabel(row, text=f"#{record['user_id']}" if record['user_id'] else "-", font=("Segoe UI", 11, "bold"), width=60, anchor="w", text_color=self.COLORS["primary"]).pack(side="left", padx=5)
            ctk.CTkLabel(row, text=record["name"], font=("Segoe UI", 12, "bold"), anchor="w", text_color=self.COLORS["text_dark"]).pack(side="left", fill="x", expand=True, padx=10)

            # Status Badge
            badge = ctk.CTkLabel(
                row,
                text="🟢 VERIFIED" if is_success else "🔴 DENIED",
                font=("Segoe UI", 11, "bold"),
                fg_color=self.COLORS["success_bg"] if is_success else self.COLORS["danger_bg"],
                text_color=self.COLORS["success"] if is_success else self.COLORS["danger"],
                corner_radius=6,
                width=120,
                pady=3
            )
            badge.pack(side="left", padx=10)

            ctk.CTkLabel(row, text=record["file"], font=("Consolas", 11), width=150, anchor="e", text_color=self.COLORS["text_muted"]).pack(side="right", padx=10)

    def clear_login_logs(self):
        if messagebox.askyesno("Clear Logs", "Are you sure you want to clear all user verification logs?"):
            self.login_history.clear()
            self.render_login_log_table()

    def export_login_log_csv(self):
        if not self.login_history:
            messagebox.showinfo("Export Empty", "No logs available to export.")
            return

        filepath = filedialog.asksaveasfilename(defaultextension=".csv", filetypes=[("CSV Files", "*.csv")])
        if filepath:
            try:
                with open(filepath, "w") as f:
                    f.write("Timestamp,User ID,Name,Status,Confidence,Auth File\n")
                    for r in self.login_history:
                        f.write(f'"{r["timestamp"]}",{r["user_id"]},"{r["name"]}",{r["status"]},{r["confidence"]},"{r["file"]}"\n')
                messagebox.showinfo("Export Success", f"Logs exported to {filepath}")
            except Exception as e:
                messagebox.showerror("Export Error", str(e))

    # --------------------------------------------------------------------------
    # Tab 5: SCP Files (C:\tmp)
    # --------------------------------------------------------------------------
    def setup_scp_tab(self):
        container = ctk.CTkFrame(self.tab_scp, fg_color="transparent")
        container.pack(fill="both", expand=True, padx=20, pady=20)

        # Header Info Card
        info_card = ctk.CTkFrame(
            container,
            fg_color=self.COLORS["card"],
            border_width=1,
            border_color=self.COLORS["border"],
            corner_radius=16
        )
        info_card.pack(fill="x", pady=(0, 15))

        ctk.CTkLabel(
            info_card,
            text=f"📂 Destination Directory: {TARGET_DIR} (Port {SCP_PORT})",
            font=("Segoe UI", 14, "bold"),
            text_color=self.COLORS["text_dark"]
        ).pack(side="left", padx=20, pady=15)

        ctk.CTkButton(
            info_card,
            text="Open Folder 📁",
            font=("Segoe UI", 12, "bold"),
            fg_color=self.COLORS["bg"],
            text_color=self.COLORS["text_dark"],
            hover_color=self.COLORS["border"],
            width=130,
            command=lambda: os.startfile(TARGET_DIR) if os.name == 'nt' else None
        ).pack(side="right", padx=20, pady=15)

        # Main Split Frame
        split_frame = ctk.CTkFrame(container, fg_color="transparent")
        split_frame.pack(fill="both", expand=True)

        # File Received List Scrollable
        self.scp_scroll = ctk.CTkScrollableFrame(
            split_frame,
            fg_color=self.COLORS["card"],
            border_width=1,
            border_color=self.COLORS["border"],
            corner_radius=16,
            width=400
        )
        self.scp_scroll.pack(side="left", fill="both", padx=(0, 15))

        # File Decryption Inspector Details
        self.scp_inspector = ctk.CTkFrame(
            split_frame,
            fg_color=self.COLORS["card"],
            border_width=1,
            border_color=self.COLORS["border"],
            corner_radius=16
        )
        self.scp_inspector.pack(side="left", fill="both", expand=True)

        ctk.CTkLabel(
            self.scp_inspector,
            text="AES Decryption Inspector",
            font=("Segoe UI", 16, "bold"),
            text_color=self.COLORS["text_dark"]
        ).pack(anchor="w", padx=20, pady=(20, 10))

        self.scp_decrypt_text = ctk.CTkTextbox(
            self.scp_inspector,
            font=("Consolas", 12),
            fg_color=self.COLORS["bg"],
            text_color=self.COLORS["text_dark"]
        )
        self.scp_decrypt_text.pack(fill="both", expand=True, padx=20, pady=(0, 20))

        self.refresh_scp_file_list()

    def refresh_scp_file_list(self):
        for child in self.scp_scroll.winfo_children():
            child.destroy()

        ctk.CTkLabel(
            self.scp_scroll,
            text="Received Encrypted Auth Files",
            font=("Segoe UI", 14, "bold"),
            text_color=self.COLORS["text_dark"]
        ).pack(anchor="w", padx=15, pady=10)

        files = [f for f in os.listdir(TARGET_DIR) if f.endswith(".enc")]
        if not files:
            ctk.CTkLabel(
                self.scp_scroll,
                text="No .enc files received yet in C:\\tmp.",
                font=("Segoe UI", 12),
                text_color=self.COLORS["text_muted"]
            ).pack(pady=30)
            return

        for fname in sorted(files, reverse=True):
            fpath = os.path.join(TARGET_DIR, fname)
            is_success = "success" in fname.lower()

            btn = ctk.CTkButton(
                self.scp_scroll,
                text=f"{'🟢' if is_success else '🔴'} {fname}",
                font=("Segoe UI", 12, "bold"),
                anchor="w",
                fg_color=self.COLORS["success_bg"] if is_success else self.COLORS["danger_bg"],
                text_color=self.COLORS["success"] if is_success else self.COLORS["danger"],
                hover_color=self.COLORS["border"],
                command=lambda path=fpath, name=fname: self.inspect_scp_file(path, name)
            )
            btn.pack(fill="x", padx=10, pady=4)

    def inspect_scp_file(self, filepath, filename):
        try:
            with open(filepath, "r") as f:
                hex_content = f.read().strip()

            decrypted_str = decrypt_aes128_hex(hex_content)

            self.scp_decrypt_text.delete("1.0", "end")
            self.scp_decrypt_text.insert("end", f"=== FILE: {filename} ===\n")
            self.scp_decrypt_text.insert("end", f"Path: {filepath}\n")
            self.scp_decrypt_text.insert("end", f"Received Time: {datetime.now().strftime('%H:%M:%S')}\n\n")
            self.scp_decrypt_text.insert("end", f"--- ENCRYPTED HEX PAYLOAD ---\n{hex_content[:64]}...\n\n")
            self.scp_decrypt_text.insert("end", f"--- AES-128 DECRYPTED JSON ---\n{decrypted_str}\n")
        except Exception as e:
            self.scp_decrypt_text.delete("1.0", "end")
            self.scp_decrypt_text.insert("end", f"Error reading file: {e}")

    # --------------------------------------------------------------------------
    # Tab 6: Telemetry Logs
    # --------------------------------------------------------------------------
    def setup_log_tab(self):
        container = ctk.CTkFrame(self.tab_log, fg_color="transparent")
        container.pack(fill="both", expand=True, padx=20, pady=20)

        self.log_text = ctk.CTkTextbox(
            container,
            font=("Consolas", 11),
            fg_color=self.COLORS["card"],
            border_width=1,
            border_color=self.COLORS["border"],
            corner_radius=16,
            text_color=self.COLORS["text_dark"]
        )
        self.log_text.pack(fill="both", expand=True)

    def append_log(self, text):
        t_str = datetime.now().strftime("[%H:%M:%S] ")
        self.log_text.insert("end", t_str + text + "\n")
        self.log_text.see("end")

    # --------------------------------------------------------------------------
    # Navigation & Authentication Logic
    # --------------------------------------------------------------------------
    def show_lock_screen(self):
        self.is_authenticated = False
        self.main_frame.pack_forget()
        self.lock_frame.pack(fill="both", expand=True)

    def unlock_dashboard(self, user_name="Admin"):
        self.is_authenticated = True
        self.lock_frame.pack_forget()
        self.main_frame.pack(fill="both", expand=True)
        messagebox.showinfo("Access Granted", f"Welcome back, {user_name}! Fingerprint verified.")
        self.refresh_templates()

    def admin_bypass_prompt(self):
        # Admin PIN entry prompt
        dialog = ctk.CTkInputDialog(text="Enter Master Admin Key:", title="Emergency Unlock")
        key = dialog.get_input()
        if key == "admin123":
            self.unlock_dashboard("Master Admin")
        elif key:
            messagebox.showerror("Access Denied", "Invalid Master Key.")

    # --------------------------------------------------------------------------
    # Serial Communication Handler & Heartbeat
    # --------------------------------------------------------------------------
    def get_serial_ports(self):
        ports = [port.device for port in serial.tools.list_ports.comports()]
        return ports if ports else ["No Ports Found"]

    def refresh_serial_ports(self):
        ports = self.get_serial_ports()
        self.port_combo.configure(values=ports)
        if ports:
            self.port_combo.set(ports[0])

    def toggle_serial_connection(self):
        if self.serial_running:
            self.serial_running = False
            if self.serial_conn and self.serial_conn.is_open:
                self.serial_conn.close()
            self.btn_connect.configure(text="Connect ESP32", fg_color=self.COLORS["primary"])
            self.lock_status_label.configure(text="● Disconnected from ESP32 Serial", text_color=self.COLORS["danger"])
            return

        port = self.port_combo.get()
        if not port or port == "No Ports Found":
            messagebox.showerror("Serial Error", "Please select a valid COM port!")
            return

        try:
            self.serial_conn = serial.Serial(port, 115200, timeout=1)
            self.serial_running = True
            self.serial_thread = threading.Thread(target=self.read_serial_loop, daemon=True)
            self.serial_thread.start()

            self.heartbeat_thread = threading.Thread(target=self.heartbeat_loop, daemon=True)
            self.heartbeat_thread.start()

            self.btn_connect.configure(text="Disconnect 🔌", fg_color=self.COLORS["danger"])
            self.lock_status_label.configure(text=f"● Connected to {port} (Checking stored templates...)", text_color=self.COLORS["primary"])
            self.send_serial_cmd("ping")
            self.send_serial_cmd("l")
        except Exception as e:
            messagebox.showerror("Serial Connection Error", str(e))

    def heartbeat_loop(self):
        while self.serial_running and self.serial_conn and self.serial_conn.is_open:
            time.sleep(3)
            if self.serial_running:
                self.send_serial_cmd("ping")

    def send_serial_cmd(self, cmd):
        if self.serial_conn and self.serial_conn.is_open:
            try:
                self.serial_conn.write((cmd + "\n").encode('utf-8'))
            except Exception:
                pass

    def read_serial_loop(self):
        while self.serial_running and self.serial_conn and self.serial_conn.is_open:
            try:
                line = self.serial_conn.readline().decode('utf-8', errors='ignore').strip()
                if line:
                    self.after(0, self.handle_serial_data, line)
            except Exception:
                break

    def handle_serial_data(self, line):
        self.append_log(f"ESP32 -> {line}")
        try:
            data = json.loads(line)
            event = data.get("event", "")

            # Verification Event
            if event == "verify":
                status = data.get("status", "")
                confidence = data.get("confidence", 0)
                if status == "success":
                    uid = data.get("id", 0)
                    uname = data.get("name", "User")
                    self.lock_icon_label.configure(text="🔓")
                    self.lock_status_label.configure(
                        text=f"● Verification Success! Welcome {uname}",
                        text_color=self.COLORS["success"]
                    )
                    self.add_login_log_entry(uid, uname, "SUCCESS", confidence, "auth_success.enc")
                    if not self.is_authenticated:
                        self.after(500, lambda: self.unlock_dashboard(uname))
                else:
                    self.lock_icon_label.configure(text="🔒")
                    self.lock_status_label.configure(
                        text="● Verification Failed! Access Denied.",
                        text_color=self.COLORS["danger"]
                    )
                    self.add_login_log_entry(None, "Unrecognized Finger", "FAILED", 0, "auth_false.enc")

            # Pong Heartbeat / Status Event
            elif event == "pong":
                count = data.get("count", -1)
                stations = data.get("stations", [])
                stations_count = data.get("stations_count", len(stations))

                self.ap_badge.configure(text=f"📡 ESP32 AP: 192.168.4.1 ({stations_count} Connected)")
                self.render_connected_devices_table(stations)

                if count == 0 and not self.is_authenticated:
                    self.lock_icon_label.configure(text="🔓")
                    self.lock_status_label.configure(
                        text="● No registered fingerprints found. Direct access granted!",
                        text_color=self.COLORS["success"]
                    )
                    self.after(500, lambda: self.unlock_dashboard("Setup User (No Fingerprints Enrolled)"))

            # Enroll Interactive Steps Event
            elif event == "enroll_status":
                step = data.get("step", "")
                msg = data.get("msg", "")
                if step == "place_1":
                    self.enroll_step_icon.configure(text="👆")
                    self.enroll_step_title.configure(text="Step 1: Place Finger")
                    self.enroll_step_msg.configure(text=msg)
                elif step == "remove":
                    self.enroll_step_icon.configure(text="🖐️")
                    self.enroll_step_title.configure(text="Step 2: Remove Finger")
                    self.enroll_step_msg.configure(text=msg)
                elif step == "place_2":
                    self.enroll_step_icon.configure(text="👆")
                    self.enroll_step_title.configure(text="Step 3: Place Same Finger Again")
                    self.enroll_step_msg.configure(text=msg)
                elif step == "success":
                    self.enroll_step_icon.configure(text="✅")
                    self.enroll_step_title.configure(text="Enrollment Successful!")
                    self.enroll_step_msg.configure(text=f"Registered #{data.get('id')} ({data.get('name')})")
                    self.refresh_templates()
                elif step == "error":
                    self.enroll_step_icon.configure(text="❌")
                    self.enroll_step_title.configure(text="Enrollment Error")
                    self.enroll_step_msg.configure(text=msg)

            # Template List Event
            elif event == "list":
                templates = data.get("templates", [])
                count = data.get("count", len(templates))
                self.render_user_list(templates)
                if count == 0 and not self.is_authenticated:
                    self.lock_icon_label.configure(text="🔓")
                    self.lock_status_label.configure(
                        text="● No registered fingerprints found. Direct access granted!",
                        text_color=self.COLORS["success"]
                    )
                    self.after(500, lambda: self.unlock_dashboard("Setup User (No Fingerprints Enrolled)"))

        except json.JSONDecodeError:
            pass

    # --------------------------------------------------------------------------
    # User Commands
    # --------------------------------------------------------------------------
    def start_enrollment(self):
        uid = self.entry_id.get().strip()
        uname = self.entry_name.get().strip()

        if not uid or not uname:
            messagebox.showwarning("Missing Field", "Please fill in both Fingerprint ID and Full Name!")
            return

        if not self.serial_running:
            messagebox.showwarning("Serial Disconnected", "Please connect to ESP32 Serial Port first!")
            return

        self.send_serial_cmd(f"e {uid} {uname}")

    def refresh_templates(self):
        if self.serial_running:
            self.send_serial_cmd("l")

    def delete_template(self, uid):
        if messagebox.askyesno("Confirm Delete", f"Are you sure you want to delete template #{uid}?"):
            if self.serial_running:
                self.send_serial_cmd(f"d {uid}")
                self.after(500, self.refresh_templates)

    def on_scp_file_received(self, filename, hex_content, client_ip):
        self.after(0, self.refresh_scp_file_list)
        self.after(0, lambda: self.append_log(f"SCP File Received: {filename} from {client_ip}"))

# ==============================================================================
# Main Entry Point
# ==============================================================================
if __name__ == "__main__":
    app = OSLoaderApp()
    app.mainloop()
