import sys
import os
import json
import time
import socket
import threading
import urllib.request
from datetime import datetime
from http.server import HTTPServer, BaseHTTPRequestHandler

# Set stdout/stderr encoding for Windows console compatibility
if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding='utf-8')
        sys.stderr.reconfigure(encoding='utf-8')
    except Exception:
        pass

# ==============================================================================
# Auto-Install Crypto Dependency if needed
# ==============================================================================
try:
    from Crypto.Cipher import AES
except ImportError:
    print("[!] Installing required package 'pycryptodome'...")
    import subprocess
    subprocess.run([sys.executable, "-m", "pip", "install", "pycryptodome"], check=True)
    from Crypto.Cipher import AES

# ==============================================================================
# Configuration
# ==============================================================================
AES_KEY = b'MySecr3tAESKey!!'  # 16 bytes matching ESP32
AES_IV  = bytes(range(16))     # 0x00..0x0F matching ESP32
TARGET_DIR = r"C:\tmp"
PORTS = [5000, 2222]

os.makedirs(TARGET_DIR, exist_ok=True)

def decrypt_aes128_hex(hex_str):
    """Decrypts AES-128-CBC hex payload generated by ESP32."""
    try:
        cipher_bytes = bytes.fromhex(hex_str.strip())
        cipher = AES.new(AES_KEY, AES.MODE_CBC, AES_IV)
        decrypted = cipher.decrypt(cipher_bytes)
        # Remove PKCS7 padding
        pad_len = decrypted[-1]
        if pad_len <= 16:
            decrypted = decrypted[:-pad_len]
        return decrypted.decode('utf-8', errors='ignore')
    except Exception as e:
        return f"Decryption Error: {e}"

last_processed_hex = ""

def process_received_file(filename, hex_content, client_ip, method_label):
    global last_processed_hex
    if not hex_content or hex_content == last_processed_hex:
        return
    
    last_processed_hex = hex_content
    filepath = os.path.join(TARGET_DIR, filename)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Save raw file to C:\tmp
    with open(filepath, "w") as f:
        f.write(hex_content)

    # Decrypt content
    decrypted_json = decrypt_aes128_hex(hex_content)

    print("\n" + "=" * 65)
    print(f" [+] [{timestamp}] FILE RECEIVED via {method_label}")
    print("=" * 65)
    print(f" Source Device IP : {client_ip}")
    print(f" Saved File Path  : {filepath}")
    print(f" Raw Encrypted Hex: {hex_content[:48]}...")
    print("-" * 65)
    print(" [*] DECRYPTED AES-128 JSON PAYLOAD:")
    print(f" {decrypted_json}")
    print("=" * 65 + "\n")

# ==============================================================================
# HTTP Request Handler
# ==============================================================================
class AuthFileHTTPRequestHandler(BaseHTTPRequestHandler):
    def do_POST(self):
        try:
            length = int(self.headers.get('Content-Length', 0))
            body = self.rfile.read(length).decode('utf-8', errors='ignore')

            filename = "auth_status.enc"
            hex_content = ""

            try:
                data = json.loads(body)
                filename = data.get("filename", "auth_status.enc")
                hex_content = data.get("data", "")
            except Exception:
                hex_content = body.strip()

            if "success" in filename.lower():
                filename = "auth_success.enc"
            elif "false" in filename.lower():
                filename = "auth_false.enc"

            client_ip = self.client_address[0]
            server_port = self.server.server_port

            process_received_file(filename, hex_content, client_ip, f"HTTP POST Port {server_port}")

            # Send HTTP 200 Response
            self.send_response(200)
            self.send_header('Content-Type', 'application/json')
            self.send_header('Access-Control-Allow-Origin', '*')
            self.end_headers()
            self.wfile.write(b'{"status":"success","message":"File saved to C:\\\\tmp"}')

        except Exception as e:
            print(f"[!] Error handling HTTP POST request: {e}")
            self.send_response(500)
            self.end_headers()

    def log_message(self, format, *args):
        # Silence default HTTP server logging for cleaner console output
        pass

# ==============================================================================
# Server Runners (HTTP Server, UDP Broadcast Listener & Poller)
# ==============================================================================
def start_http_server_on_port(port):
    try:
        httpd = HTTPServer(('0.0.0.0', port), AuthFileHTTPRequestHandler)
        print(f" [*] HTTP POST Server active on port {port}")
        httpd.serve_forever()
    except Exception as e:
        print(f" [!] Could not bind HTTP Server on port {port}: {e}")

def start_udp_listener_on_port(port):
    udp_sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    udp_sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    try:
        udp_sock.bind(("0.0.0.0", port))
        print(f" [*] UDP Broadcast Listener active on port {port}")
    except Exception as e:
        print(f" [!] Could not bind UDP listener on port {port}: {e}")
        return

    while True:
        try:
            data, addr = udp_sock.recvfrom(8192)
            text = data.decode('utf-8', errors='ignore').strip()
            if text.startswith("SCP_TRANSFER"):
                parts = text.split(" ", 2)
                if len(parts) >= 3:
                    filename = parts[1]
                    hex_content = parts[2]
                    process_received_file(filename, hex_content, addr[0], f"UDP Hotspot Broadcast Port {port}")
        except Exception:
            time.sleep(0.1)

def poll_esp32_http_endpoint():
    print(" [*] ESP32 Wi-Fi Hotspot HTTP Poller active (http://192.168.4.1/)...")
    while True:
        try:
            req = urllib.request.Request("http://192.168.4.1/", headers={'User-Agent': 'Mozilla/5.0'})
            with urllib.request.urlopen(req, timeout=1) as response:
                hex_content = response.read().decode('utf-8', errors='ignore').strip()
                if hex_content and hex_content != last_processed_hex:
                    filename = "auth_success.enc" if "true" in decrypt_aes128_hex(hex_content).lower() else "auth_false.enc"
                    process_received_file(filename, hex_content, "192.168.4.1", "HTTP Hotspot Endpoint")
        except Exception:
            pass
        time.sleep(2)

if __name__ == "__main__":
    print("=" * 65)
    print("   OSLoader - Standalone ESP32 Multi-Protocol File Receiver")
    print("=" * 65)
    print(f" [*] Destination Directory : {TARGET_DIR}")
    print(f" [*] Monitored Ports       : {PORTS}")
    print(" [*] Listening for ESP32 HTTP POST, UDP Broadcast & Hotspot HTTP...")
    print("=" * 65 + "\n")

    threads = []
    for port in PORTS:
        t_http = threading.Thread(target=start_http_server_on_port, args=(port,), daemon=True)
        t_http.start()
        threads.append(t_http)

        t_udp = threading.Thread(target=start_udp_listener_on_port, args=(port,), daemon=True)
        t_udp.start()
        threads.append(t_udp)

    t_poll = threading.Thread(target=poll_esp32_http_endpoint, daemon=True)
    t_poll.start()
    threads.append(t_poll)

    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        print("\n[*] Shutting down Receiver Server...")
        sys.exit(0)
