import sys
import os
import subprocess
import json
import time
import threading
import shutil
import socket
import urllib.request
from datetime import datetime

# ==============================================================================
# Executable & CustomTkinter Asset Path Patch (for Frozen Executables)
# ==============================================================================
if getattr(sys, 'frozen', False):
    import builtins
    _orig_open = builtins.open
    def _custom_open(file, *args, **kwargs):
        try:
            file_str = os.fspath(file) if isinstance(file, (str, bytes, os.PathLike)) else str(file)
            if "customtkinter" in file_str and (".exe" in file_str or ".zip" in file_str):
                exe_dir = os.path.dirname(sys.executable)
                idx = file_str.find("customtkinter")
                if idx != -1:
                    file = os.path.join(exe_dir, file_str[idx:])
        except Exception:
            pass
        return _orig_open(file, *args, **kwargs)
    builtins.open = _custom_open

# ==============================================================================
# Auto-Install Missing Dependencies (Skipped when running as frozen .exe)
# ==============================================================================
REQUIRED_PACKAGES = [
    "customtkinter",
    "pycryptodome",
    "pillow",
    "pyserial",
    "psutil"
]

def auto_install_dependencies():
    if getattr(sys, 'frozen', False):
        return

    missing = []
    for pkg in REQUIRED_PACKAGES:
        try:
            if pkg == "pycryptodome":
                __import__("Crypto")
            elif pkg == "pillow":
                __import__("PIL")
            else:
                __import__(pkg)
        except ImportError:
            missing.append(pkg)

    if missing:
        print(f"Installing missing dependencies: {missing}...")
        try:
            subprocess.run([sys.executable, "-m", "pip", "install"] + missing, check=True)
            print("Dependencies installed successfully!")
        except Exception as e:
            print(f"Warning: Failed auto-installing dependencies: {e}")

auto_install_dependencies()

# Standard Library & Third-Party Imports
import customtkinter as ctk
from tkinter import messagebox, filedialog
from Crypto.Cipher import AES

# Set CustomTkinter Appearance
ctk.set_appearance_mode("light")
ctk.set_default_color_theme("blue")

# ==============================================================================
# Path & Directory Configuration (Portable - Relative to Workspace)
# ==============================================================================
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
HDD_DIR  = os.path.join(BASE_DIR, "HDD")
TMP_DIR  = r"C:\tmp"
AES_KEY  = b'MySecr3tAESKey!!'  # 16 bytes matching ESP32
AES_IV   = bytes(range(16))     # 0x00..0x0F matching ESP32

os.makedirs(HDD_DIR, exist_ok=True)
os.makedirs(TMP_DIR, exist_ok=True)

# Standard VMware Installation Search Paths
VMWARE_SEARCH_PATHS = [
    r"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe",
    r"C:\Program Files\VMware\VMware Workstation\vmrun.exe",
    r"C:\Program Files (x86)\VMware\VMware Player\vmrun.exe",
    r"C:\Program Files\VMware\VMware Player\vmrun.exe",
]

def find_vmware_tool(tool_name="vmrun.exe"):
    """Locates vmrun.exe or vmware-vdiskmanager.exe on Windows."""
    # 1. Check system PATH
    found = shutil.which(tool_name)
    if found:
        return found

    # 2. Check standard installation folders
    for base_path in VMWARE_SEARCH_PATHS:
        dir_path = os.path.dirname(base_path)
        target = os.path.join(dir_path, tool_name)
        if os.path.exists(target):
            return target

    return ""

def decrypt_aes128_hex(hex_str):
    """Decrypts AES-128-CBC hex payload generated by ESP32."""
    try:
        cipher_bytes = bytes.fromhex(hex_str.strip())
        cipher = AES.new(AES_KEY, AES.MODE_CBC, AES_IV)
        decrypted = cipher.decrypt(cipher_bytes)
        pad_len = decrypted[-1]
        if pad_len <= 16:
            decrypted = decrypted[:-pad_len]
        return decrypted.decode('utf-8', errors='ignore')
    except Exception as e:
        return f"Decryption Error: {e}"

# ==============================================================================
# Embedded HTTP Receiver & ESP32 Auth Monitor
# ==============================================================================
from http.server import HTTPServer, BaseHTTPRequestHandler

class EmbeddedHTTPAuthReceiver:
    def __init__(self, callback):
        self.callback = callback
        self.running = True

        self.t1 = threading.Thread(target=self._run_http_server, args=(5000,), daemon=True)
        self.t2 = threading.Thread(target=self._run_http_server, args=(2222,), daemon=True)
        self.t3 = threading.Thread(target=self._poll_hotspot, daemon=True)

    def start(self):
        self.t1.start()
        self.t2.start()
        self.t3.start()

    def _save_and_notify(self, filename, hex_content, client_ip):
        filepath = os.path.join(TMP_DIR, filename)
        try:
            with open(filepath, "w") as f:
                f.write(hex_content)
            if self.callback:
                self.callback(filename, hex_content, client_ip)
        except Exception as e:
            print(f"Error saving auth file: {e}")

    def _run_http_server(self, port):
        callback_ref = self._save_and_notify

        class Handler(BaseHTTPRequestHandler):
            def do_POST(self):
                try:
                    length = int(self.headers.get('Content-Length', 0))
                    body = self.rfile.read(length).decode('utf-8', errors='ignore')
                    filename = "auth_status.enc"
                    hex_content = ""
                    try:
                        data = json.loads(body)
                        filename = data.get("filename", "auth_status.enc")
                        hex_content = data.get("data", "")
                    except Exception:
                        hex_content = body.strip()

                    if "success" in filename.lower():
                        filename = "auth_success.enc"
                    elif "false" in filename.lower():
                        filename = "auth_false.enc"

                    callback_ref(filename, hex_content, self.client_address[0])
                    self.send_response(200)
                    self.end_headers()
                except Exception:
                    self.send_response(500)
                    self.end_headers()

            def log_message(self, format, *args):
                pass

        try:
            httpd = HTTPServer(('0.0.0.0', port), Handler)
            httpd.serve_forever()
        except Exception:
            pass

    def _poll_hotspot(self):
        last_hex = ""
        while self.running:
            try:
                req = urllib.request.Request("http://192.168.4.1/", headers={'User-Agent': 'Mozilla/5.0'})
                with urllib.request.urlopen(req, timeout=1) as response:
                    hex_content = response.read().decode('utf-8', errors='ignore').strip()
                    if hex_content and hex_content != last_hex:
                        last_hex = hex_content
                        dec = decrypt_aes128_hex(hex_content)
                        fn = "auth_success.enc" if "true" in dec.lower() else "auth_false.enc"
                        self._save_and_notify(fn, hex_content, "192.168.4.1")
            except Exception:
                pass
            time.sleep(2)

# ==============================================================================
# Main VMware OS Loader & Installer Application
# ==============================================================================
class VMwareOSLoaderApp(ctk.CTk):
    def __init__(self):
        super().__init__()

        self.title("VMware OS Loader & Installer - ESP32 Fingerprint Authenticated")
        self.geometry("1180x780")
        self.minsize(1000, 680)

        # State & Path Discovery
        self.vmrun_path = find_vmware_tool("vmrun.exe")
        self.vdiskmanager_path = find_vmware_tool("vmware-vdiskmanager.exe")

        self.latest_auth_status = False
        self.latest_user_name = "None"
        self.latest_auth_time = "Never"

        # Colors System (Light Modern Theme)
        self.COLORS = {
            "bg": "#F8F9FA",
            "card": "#FFFFFF",
            "border": "#E2E8F0",
            "primary": "#2563EB",
            "primary_hover": "#1D4ED8",
            "success": "#16A34A",
            "success_bg": "#DCFCE7",
            "danger": "#DC2626",
            "danger_bg": "#FEE2E2",
            "warning": "#D97706",
            "warning_bg": "#FEF3C7",
            "text_dark": "#0F172A",
            "text_muted": "#64748B"
        }

        self.configure(fg_color=self.COLORS["bg"])

        # Start Embedded HTTP Auth Listener
        self.http_receiver = EmbeddedHTTPAuthReceiver(self.on_auth_file_received)
        self.http_receiver.start()

        # Check existing C:\tmp\auth_success.enc on launch
        self.check_existing_auth_file()

        # Build UI
        self.build_header()
        self.build_main_content()

    # --------------------------------------------------------------------------
    # Header Bar Layout
    # --------------------------------------------------------------------------
    def build_header(self):
        header = ctk.CTkFrame(
            self,
            fg_color=self.COLORS["card"],
            corner_radius=12,
            border_width=1,
            border_color=self.COLORS["border"],
            height=70
        )
        header.pack(fill="x", side="top", padx=20, pady=(15, 10))

        ctk.CTkLabel(
            header,
            text="🖥️ VMware OS Loader & Installer (HDD Storage)",
            font=("Segoe UI", 18, "bold"),
            text_color=self.COLORS["text_dark"]
        ).pack(side="left", padx=20, pady=15)

        # Status Badges
        self.auth_badge = ctk.CTkLabel(
            header,
            text="🔒 ESP Auth: Pending Scan",
            font=("Segoe UI", 12, "bold"),
            fg_color=self.COLORS["danger_bg"],
            text_color=self.COLORS["danger"],
            corner_radius=8,
            padx=12,
            pady=6
        )
        self.auth_badge.pack(side="right", padx=15, pady=12)

        self.vmware_badge = ctk.CTkLabel(
            header,
            text=f"⚙️ VMware CLI: {'Found' if self.vmrun_path else 'Not Found'}",
            font=("Segoe UI", 12, "bold"),
            fg_color=self.COLORS["success_bg"] if self.vmrun_path else self.COLORS["warning_bg"],
            text_color=self.COLORS["success"] if self.vmrun_path else self.COLORS["warning"],
            corner_radius=8,
            padx=12,
            pady=6
        )
        self.vmware_badge.pack(side="right", padx=5, pady=12)

    # --------------------------------------------------------------------------
    # Main Content Area (Tabview)
    # --------------------------------------------------------------------------
    def build_main_content(self):
        self.tabview = ctk.CTkTabview(
            self,
            fg_color=self.COLORS["card"],
            segmented_button_fg_color=self.COLORS["bg"],
            segmented_button_selected_color=self.COLORS["primary"],
            segmented_button_selected_hover_color=self.COLORS["primary_hover"],
            corner_radius=16
        )
        self.tabview.pack(fill="both", expand=True, padx=20, pady=(5, 15))

        self.tab_vms = self.tabview.add("🖥️ Installed Virtual Machines")
        self.tab_create = self.tabview.add("➕ Install New OS / Create VM")
        self.tab_auth = self.tabview.add("🔐 ESP32 Auth & Telemetry")
        self.tab_settings = self.tabview.add("⚙️ VMware Settings")

        self.setup_vms_tab()
        self.setup_create_tab()
        self.setup_auth_tab()
        self.setup_settings_tab()

    # --------------------------------------------------------------------------
    # Tab 1: Installed VMs Management & Execution
    # --------------------------------------------------------------------------
    def setup_vms_tab(self):
        container = ctk.CTkFrame(self.tab_vms, fg_color="transparent")
        container.pack(fill="both", expand=True, padx=20, pady=20)

        top_bar = ctk.CTkFrame(container, fg_color="transparent")
        top_bar.pack(fill="x", pady=(0, 15))

        ctk.CTkLabel(
            top_bar,
            text=f"Installed Virtual Machines in HDD Directory ({HDD_DIR})",
            font=("Segoe UI", 16, "bold"),
            text_color=self.COLORS["text_dark"]
        ).pack(side="left")

        ctk.CTkButton(
            top_bar,
            text="Refresh List 🔄",
            font=("Segoe UI", 12, "bold"),
            fg_color=self.COLORS["primary"],
            hover_color=self.COLORS["primary_hover"],
            width=130,
            command=self.refresh_vm_list
        ).pack(side="right")

        # Scrollable VMs List
        self.vm_scroll = ctk.CTkScrollableFrame(
            container,
            fg_color=self.COLORS["card"],
            border_width=1,
            border_color=self.COLORS["border"],
            corner_radius=16
        )
        self.vm_scroll.pack(fill="both", expand=True)

        self.refresh_vm_list()

    def get_running_vmx_list(self):
        """Query running VMs via vmrun list command."""
        running = []
        if not self.vmrun_path or not os.path.exists(self.vmrun_path):
            return running

        for target in ["ws", "player"]:
            try:
                cmd = [self.vmrun_path, "-T", target, "list"]
                output = subprocess.check_output(cmd, stderr=subprocess.DEVNULL, text=True)
                for line in output.splitlines():
                    if line.endswith(".vmx"):
                        running.append(os.path.normpath(line.strip()))
                break
            except Exception:
                continue
        return running

    def refresh_vm_list(self):
        for child in self.vm_scroll.winfo_children():
            child.destroy()

        running_vms = self.get_running_vmx_list()

        # Discover VMs inside HDD directory
        vms = []
        if os.path.exists(HDD_DIR):
            for item in os.listdir(HDD_DIR):
                item_path = os.path.join(HDD_DIR, item)
                if os.path.isdir(item_path):
                    # Look for .vmx configuration file
                    for file in os.listdir(item_path):
                        if file.endswith(".vmx"):
                            vmx_path = os.path.normpath(os.path.join(item_path, file))
                            is_running = any(r.lower() == vmx_path.lower() for r in running_vms)
                            vms.append({
                                "name": item,
                                "file": file,
                                "path": vmx_path,
                                "running": is_running
                            })

        # Render Header
        header = ctk.CTkFrame(self.vm_scroll, fg_color=self.COLORS["bg"], height=40)
        header.pack(fill="x", padx=15, pady=5)

        ctk.CTkLabel(header, text="VM Name", font=("Segoe UI", 12, "bold"), width=180, anchor="w").pack(side="left", padx=10)
        ctk.CTkLabel(header, text="VMX Configuration Path", font=("Segoe UI", 12, "bold"), anchor="w").pack(side="left", fill="x", expand=True, padx=10)
        ctk.CTkLabel(header, text="Status", font=("Segoe UI", 12, "bold"), width=120, anchor="center").pack(side="left", padx=10)
        ctk.CTkLabel(header, text="Actions (Auth Guarded)", font=("Segoe UI", 12, "bold"), width=280, anchor="e").pack(side="right", padx=10)

        if not vms:
            ctk.CTkLabel(
                self.vm_scroll,
                text="No Virtual Machines found in HDD folder. Click 'Install New OS / Create VM' tab to build one.",
                font=("Segoe UI", 13),
                text_color=self.COLORS["text_muted"]
            ).pack(pady=50)
            return

        for vm in vms:
            row = ctk.CTkFrame(self.vm_scroll, fg_color=self.COLORS["card"], height=50)
            row.pack(fill="x", padx=15, pady=4)

            ctk.CTkLabel(row, text=f"🖥️ {vm['name']}", font=("Segoe UI", 13, "bold"), width=180, anchor="w", text_color=self.COLORS["text_dark"]).pack(side="left", padx=10)
            ctk.CTkLabel(row, text=vm["path"], font=("Consolas", 10), anchor="w", text_color=self.COLORS["text_muted"]).pack(side="left", fill="x", expand=True, padx=10)

            # Status Pill
            is_run = vm["running"]
            status_badge = ctk.CTkLabel(
                row,
                text="🟢 RUNNING" if is_run else "🔴 STOPPED",
                font=("Segoe UI", 10, "bold"),
                fg_color=self.COLORS["success_bg"] if is_run else self.COLORS["danger_bg"],
                text_color=self.COLORS["success"] if is_run else self.COLORS["danger"],
                corner_radius=6,
                width=110,
                pady=3
            )
            status_badge.pack(side="left", padx=10)

            # Action Buttons
            btn_frame = ctk.CTkFrame(row, fg_color="transparent")
            btn_frame.pack(side="right", padx=10)

            btn_start = ctk.CTkButton(
                btn_frame,
                text="Start OS ▶️",
                font=("Segoe UI", 11, "bold"),
                fg_color=self.COLORS["primary"],
                hover_color=self.COLORS["primary_hover"],
                width=90,
                command=lambda path=vm["path"], name=vm["name"]: self.start_vm_guarded(path, name)
            )
            btn_start.pack(side="left", padx=3)

            btn_stop = ctk.CTkButton(
                btn_frame,
                text="Stop ⏹️",
                font=("Segoe UI", 11, "bold"),
                fg_color=self.COLORS["warning_bg"],
                text_color=self.COLORS["warning"],
                hover_color="#FDE68A",
                width=75,
                command=lambda path=vm["path"]: self.control_vm(path, "stop")
            )
            btn_stop.pack(side="left", padx=3)

            btn_del = ctk.CTkButton(
                btn_frame,
                text="Delete 🗑️",
                font=("Segoe UI", 11, "bold"),
                fg_color=self.COLORS["danger_bg"],
                text_color=self.COLORS["danger"],
                hover_color="#FCA5A5",
                width=75,
                command=lambda name=vm["name"]: self.delete_vm(name)
            )
            btn_del.pack(side="left", padx=3)

    # --------------------------------------------------------------------------
    # Fingerprint Guarded VM Start Execution & Token Deletion
    # --------------------------------------------------------------------------
    def start_vm_guarded(self, vmx_path, vm_name):
        """Verifies ESP32 Fingerprint Auth File, launches VM, and DELETES the auth file."""
        # Check latest auth file state
        self.check_existing_auth_file()

        if not self.latest_auth_status:
            messagebox.showerror(
                "Access Denied - Fingerprint Required",
                f"Cannot start Virtual Machine '{vm_name}'!\n\n"
                "🔒 ESP32 Fingerprint Verification is REQUIRED.\n"
                "Please touch an enrolled finger on the ESP32 scanner to unlock VM execution."
            )
            return

        user_name = self.latest_user_name
        launched = False
        vm_dir = os.path.dirname(self.vmrun_path) if self.vmrun_path else ""

        # 1. Try launching direct VMware Workstation / Player GUI executable in a separate window
        if vm_dir and os.path.exists(vm_dir):
            vmware_exe = os.path.join(vm_dir, "vmware.exe")
            vmplayer_exe = os.path.join(vm_dir, "vmplayer.exe")

            if os.path.exists(vmware_exe):
                try:
                    subprocess.Popen([vmware_exe, vmx_path])
                    launched = True
                except Exception:
                    pass

            if not launched and os.path.exists(vmplayer_exe):
                try:
                    subprocess.Popen([vmplayer_exe, vmx_path])
                    launched = True
                except Exception:
                    pass

        # 2. Try vmrun start command
        if not launched and self.vmrun_path and os.path.exists(self.vmrun_path):
            for target in ["ws", "player"]:
                try:
                    cmd = [self.vmrun_path, "-T", target, "start", vmx_path, "gui"]
                    subprocess.Popen(cmd)
                    launched = True
                    break
                except Exception:
                    continue

        # 3. Fallback: Native Windows file association (opens VMware in a separate window)
        if not launched:
            try:
                os.startfile(vmx_path)
                launched = True
            except Exception as e:
                messagebox.showerror("VM Launch Error", f"Could not launch VMware window for '{vm_name}':\n{e}")
                return

        if launched:
            # Delete authentication file from C:\tmp and reset auth status
            self.consume_and_delete_auth_files()

            messagebox.showinfo(
                "VM Starting",
                f"🟢 Fingerprint Verified ({user_name})!\n\n"
                "Authentication token consumed and deleted from C:\\tmp.\n"
                f"Opening VMware in a separate window for '{vm_name}'..."
            )
            self.after(3000, self.refresh_vm_list)

    def consume_and_delete_auth_files(self):
        """Deletes authentication files from C:\tmp and resets status."""
        for fn in ["auth_success.enc", "auth_false.enc", "auth_status.enc"]:
            fpath = os.path.join(TMP_DIR, fn)
            if os.path.exists(fpath):
                try:
                    os.remove(fpath)
                except Exception:
                    pass

        self.latest_auth_status = False
        self.latest_user_name = "Consumed / Expired"
        self.latest_auth_time = datetime.now().strftime("%H:%M:%S (Deleted)")

        self.auth_badge.configure(
            text="🔒 ESP Auth: Pending Scan",
            fg_color=self.COLORS["danger_bg"],
            text_color=self.COLORS["danger"]
        )
        self.update_auth_telemetry_ui()

    def control_vm(self, vmx_path, action="stop", mode="hard"):
        success = False

        if self.vmrun_path and os.path.exists(self.vmrun_path):
            for target in ["ws", "player"]:
                for m in [mode, "hard", "soft"]:
                    try:
                        cmd = [self.vmrun_path, "-T", target, action, vmx_path, m]
                        res = subprocess.run(cmd, capture_output=True, text=True, timeout=5)
                        if res.returncode == 0:
                            success = True
                            break
                    except Exception:
                        continue
                if success:
                    break

        # Process fallback kill on Windows if vmrun soft mode failed
        if not success and action == "stop":
            try:
                import psutil
                vmx_filename = os.path.basename(vmx_path).lower()
                for proc in psutil.process_iter(['pid', 'name', 'cmdline']):
                    if proc.info['name'] and 'vmware-vmx' in proc.info['name'].lower():
                        cmdline = " ".join(proc.info['cmdline'] or []).lower()
                        if vmx_filename in cmdline:
                            proc.kill()
                            success = True
            except Exception:
                pass

        if success or action == "stop":
            messagebox.showinfo("VM Control", f"Executed '{action}' ({mode}) command for Virtual Machine!")
        else:
            messagebox.showerror("VM Control Error", f"Could not execute '{action}' command for VM.")

        self.after(2000, self.refresh_vm_list)

    def delete_vm(self, vm_name):
        if messagebox.askyesno("Confirm Delete", f"Are you sure you want to delete VM '{vm_name}' from HDD directory?"):
            folder_path = os.path.join(HDD_DIR, vm_name)
            try:
                shutil.rmtree(folder_path)
                messagebox.showinfo("Deleted", f"Virtual Machine '{vm_name}' removed from HDD folder.")
                self.refresh_vm_list()
            except Exception as e:
                messagebox.showerror("Delete Error", str(e))

    # --------------------------------------------------------------------------
    # Tab 2: Create VM & Install OS Wizard
    # --------------------------------------------------------------------------
    def setup_create_tab(self):
        container = ctk.CTkFrame(self.tab_create, fg_color="transparent")
        container.pack(fill="both", expand=True, padx=20, pady=20)

        # Form Card
        form_card = ctk.CTkFrame(
            container,
            fg_color=self.COLORS["card"],
            border_width=1,
            border_color=self.COLORS["border"],
            corner_radius=16
        )
        form_card.pack(fill="both", expand=True, padx=10, pady=5)

        ctk.CTkLabel(
            form_card,
            text="Configure New Virtual Machine (Saved in HDD Directory)",
            font=("Segoe UI", 16, "bold"),
            text_color=self.COLORS["text_dark"]
        ).pack(anchor="w", padx=25, pady=(20, 15))

        grid_frame = ctk.CTkFrame(form_card, fg_color="transparent")
        grid_frame.pack(fill="x", padx=25, pady=5)

        # Row 1: VM Name & OS Type
        ctk.CTkLabel(grid_frame, text="VM Name:", font=("Segoe UI", 12), text_color=self.COLORS["text_muted"]).grid(row=0, column=0, sticky="w", padx=5, pady=5)
        self.entry_vm_name = ctk.CTkEntry(grid_frame, placeholder_text="e.g. Ubuntu_22_04", font=("Segoe UI", 13), width=280)
        self.entry_vm_name.grid(row=0, column=1, sticky="w", padx=(5, 30), pady=5)

        ctk.CTkLabel(grid_frame, text="Guest OS Type:", font=("Segoe UI", 12), text_color=self.COLORS["text_muted"]).grid(row=0, column=2, sticky="w", padx=5, pady=5)
        self.combo_os_type = ctk.CTkComboBox(
            grid_frame,
            values=["ubuntu-64", "debian10-64", "windows10-64", "windows11-64", "fedora-64", "other-64"],
            font=("Segoe UI", 12),
            width=220
        )
        self.combo_os_type.grid(row=0, column=3, sticky="w", padx=5, pady=5)

        # Row 2: RAM & CPU Cores
        ctk.CTkLabel(grid_frame, text="Memory RAM (MB):", font=("Segoe UI", 12), text_color=self.COLORS["text_muted"]).grid(row=1, column=0, sticky="w", padx=5, pady=15)
        self.entry_ram = ctk.CTkEntry(grid_frame, placeholder_text="2048", font=("Segoe UI", 13), width=280)
        self.entry_ram.insert(0, "2048")
        self.entry_ram.grid(row=1, column=1, sticky="w", padx=(5, 30), pady=15)

        ctk.CTkLabel(grid_frame, text="CPU Cores:", font=("Segoe UI", 12), text_color=self.COLORS["text_muted"]).grid(row=1, column=2, sticky="w", padx=5, pady=15)
        self.entry_cpu = ctk.CTkEntry(grid_frame, placeholder_text="2", font=("Segoe UI", 13), width=220)
        self.entry_cpu.insert(0, "2")
        self.entry_cpu.grid(row=1, column=3, sticky="w", padx=5, pady=15)

        # Row 3: Disk Size & ISO File Picker
        ctk.CTkLabel(grid_frame, text="Virtual Disk Size (GB):", font=("Segoe UI", 12), text_color=self.COLORS["text_muted"]).grid(row=2, column=0, sticky="w", padx=5, pady=5)
        self.entry_disk = ctk.CTkEntry(grid_frame, placeholder_text="40", font=("Segoe UI", 13), width=280)
        self.entry_disk.insert(0, "40")
        self.entry_disk.grid(row=2, column=1, sticky="w", padx=(5, 30), pady=5)

        ctk.CTkLabel(grid_frame, text="OS Installer ISO File:", font=("Segoe UI", 12), text_color=self.COLORS["text_muted"]).grid(row=2, column=2, sticky="w", padx=5, pady=5)
        iso_picker_frame = ctk.CTkFrame(grid_frame, fg_color="transparent")
        iso_picker_frame.grid(row=2, column=3, sticky="w", padx=5, pady=5)

        self.entry_iso = ctk.CTkEntry(iso_picker_frame, placeholder_text="Select .iso file...", font=("Segoe UI", 12), width=150)
        self.entry_iso.pack(side="left", padx=(0, 5))

        btn_browse_iso = ctk.CTkButton(
            iso_picker_frame,
            text="Browse 💿",
            font=("Segoe UI", 11, "bold"),
            width=65,
            command=self.browse_iso_file
        )
        btn_browse_iso.pack(side="left")

        # Submit Action Button
        btn_create = ctk.CTkButton(
            form_card,
            text="Build VM & Initialize OS Installation 💿",
            font=("Segoe UI", 14, "bold"),
            fg_color=self.COLORS["primary"],
            hover_color=self.COLORS["primary_hover"],
            height=45,
            command=self.create_virtual_machine
        )
        btn_create.pack(fill="x", padx=25, pady=(25, 20))

    def browse_iso_file(self):
        filepath = filedialog.askopenfilename(filetypes=[("ISO Disk Images", "*.iso"), ("All Files", "*.*")])
        if filepath:
            self.entry_iso.delete(0, "end")
            self.entry_iso.insert(0, filepath)

    def create_virtual_machine(self):
        name = self.entry_vm_name.get().strip().replace(" ", "_")
        os_type = self.combo_os_type.get().strip()
        ram = self.entry_ram.get().strip()
        cpu = self.entry_cpu.get().strip()
        disk_gb = self.entry_disk.get().strip()
        iso_path = self.entry_iso.get().strip()

        if not name or not ram or not cpu or not disk_gb:
            messagebox.showwarning("Missing Fields", "Please complete all required fields!")
            return

        # Target VM Folder in relative HDD directory
        vm_folder = os.path.join(HDD_DIR, name)
        os.makedirs(vm_folder, exist_ok=True)

        vmdk_path = os.path.normpath(os.path.join(vm_folder, f"{name}.vmdk"))
        vmx_path  = os.path.normpath(os.path.join(vm_folder, f"{name}.vmx"))

        # 1. Generate Virtual Disk using vmware-vdiskmanager.exe
        vdisk_cmd_executed = False
        if self.vdiskmanager_path and os.path.exists(self.vdiskmanager_path):
            try:
                cmd = [
                    self.vdiskmanager_path,
                    "-c",
                    "-s", f"{disk_gb}GB",
                    "-a", "lsilogic",
                    "-t", "1",
                    vmdk_path
                ]
                subprocess.check_output(cmd, stderr=subprocess.STDOUT)
                vdisk_cmd_executed = True
            except Exception as e:
                print(f"vmware-vdiskmanager warning: {e}")

        if not vdisk_cmd_executed:
            # Fallback descriptor generation for single monolithic/growable disk
            with open(vmdk_path, "w") as f:
                f.write('# Disk DescriptorFile\nversion=1\nencoding="UTF-8"\nCID=fffffffe\nparentCID=ffffffff\ncreateType="monolithicFlat"\n')

        # 2. Generate .vmx configuration file
        vmx_content = f""".encoding = "UTF-8"
config.version = "8"
virtualHW.version = "16"
mks.enable3D = "TRUE"
pciBridge0.present = "TRUE"
pciBridge4.present = "TRUE"
pciBridge4.virtualDev = "pcieRootPort"
pciBridge4.functions = "8"
pciBridge5.present = "TRUE"
pciBridge5.virtualDev = "pcieRootPort"
pciBridge5.functions = "8"
pciBridge6.present = "TRUE"
pciBridge6.virtualDev = "pcieRootPort"
pciBridge6.functions = "8"
pciBridge7.present = "TRUE"
pciBridge7.virtualDev = "pcieRootPort"
pciBridge7.functions = "8"
vmci0.present = "TRUE"
hpet0.present = "TRUE"
displayName = "{name}"
guestOS = "{os_type}"
nvram = "{name}.nvram"
virtualHW.productCompatibility = "hosted"
powerType.powerOff = "soft"
powerType.powerOn = "soft"
powerType.suspend = "soft"
powerType.reset = "soft"
memsize = "{ram}"
numvcpus = "{cpu}"
cpuid.coresPerSocket = "1"
scsi0.present = "TRUE"
scsi0.virtualDev = "lsilogic"
scsi0:0.present = "TRUE"
scsi0:0.fileName = "{name}.vmdk"
"""
        if iso_path and os.path.exists(iso_path):
            vmx_content += f"""ide1:0.present = "TRUE"
ide1:0.fileName = "{iso_path}"
ide1:0.deviceType = "cdrom-image"
"""
        else:
            vmx_content += """ide1:0.present = "TRUE"
ide1:0.deviceType = "cdrom-raw"
"""

        vmx_content += """ethernet0.present = "TRUE"
ethernet0.connectionType = "nat"
ethernet0.virtualDev = "e1000"
sound.present = "TRUE"
sound.virtualDev = "hdaudio"
"""

        with open(vmx_path, "w") as f:
            f.write(vmx_content)

        messagebox.showinfo(
            "VM Built Successfully",
            f"✅ Virtual Machine '{name}' configured inside HDD directory!\n\n"
            f"Folder: {vm_folder}\n"
            f"VMX File: {vmx_path}\n"
            f"Virtual Disk: {vmdk_path} ({disk_gb}GB)\n\n"
            "You can now select this VM under 'Installed Virtual Machines' tab and click 'Start OS' (fingerprint authenticated)."
        )
        self.refresh_vm_list()

    # --------------------------------------------------------------------------
    # Tab 3: ESP32 Auth & Telemetry
    # --------------------------------------------------------------------------
    def setup_auth_tab(self):
        container = ctk.CTkFrame(self.tab_auth, fg_color="transparent")
        container.pack(fill="both", expand=True, padx=20, pady=20)

        card = ctk.CTkFrame(
            container,
            fg_color=self.COLORS["card"],
            border_width=1,
            border_color=self.COLORS["border"],
            corner_radius=16
        )
        card.pack(fill="both", expand=True)

        ctk.CTkLabel(
            card,
            text="ESP32 Fingerprint Verification Status",
            font=("Segoe UI", 16, "bold"),
            text_color=self.COLORS["text_dark"]
        ).pack(anchor="w", padx=25, pady=(20, 10))

        self.auth_detail_box = ctk.CTkTextbox(
            card,
            font=("Consolas", 12),
            fg_color=self.COLORS["bg"],
            text_color=self.COLORS["text_dark"]
        )
        self.auth_detail_box.pack(fill="both", expand=True, padx=20, pady=(0, 20))

        self.update_auth_telemetry_ui()

    def update_auth_telemetry_ui(self):
        self.auth_detail_box.delete("1.0", "end")
        self.auth_detail_box.insert("end", f"=== ESP32 FINGERPRINT AUTHENTICATION STATE ===\n")
        self.auth_detail_box.insert("end", f"Status Badge       : {'🟢 AUTHENTICATED' if self.latest_auth_status else '🔴 PENDING / UNCONNECTED'}\n")
        self.auth_detail_box.insert("end", f"Decrypted User Name: {self.latest_user_name}\n")
        self.auth_detail_box.insert("end", f"Last Auth Time     : {self.latest_auth_time}\n")
        self.auth_detail_box.insert("end", f"Encrypted Auth File: C:\\tmp\\auth_success.enc\n\n")
        self.auth_detail_box.insert("end", f"--- SYSTEM RULE ---\n")
        self.auth_detail_box.insert("end", f"VM startup via 'vmrun' is strictly locked until a valid enrolled fingerprint scan\n")
        self.auth_detail_box.insert("end", f"is transmitted from the ESP32 to C:\\tmp over the Wi-Fi Hotspot network.\n")

    def check_existing_auth_file(self):
        fpath = os.path.join(TMP_DIR, "auth_success.enc")
        if os.path.exists(fpath):
            try:
                with open(fpath, "r") as f:
                    hex_str = f.read().strip()
                dec = decrypt_aes128_hex(hex_str)
                if "true" in dec.lower():
                    self.latest_auth_status = True
                    try:
                        data = json.loads(dec)
                        self.latest_user_name = data.get("user_name", "Verified User")
                    except Exception:
                        self.latest_user_name = "Verified User"
                    self.latest_auth_time = datetime.now().strftime("%H:%M:%S")
            except Exception:
                pass

    def on_auth_file_received(self, filename, hex_content, client_ip):
        decrypted = decrypt_aes128_hex(hex_content)
        is_success = "success" in filename.lower() or "true" in decrypted.lower()

        if is_success:
            self.latest_auth_status = True
            try:
                data = json.loads(decrypted)
                self.latest_user_name = data.get("user_name", "Verified User")
            except Exception:
                self.latest_user_name = "Verified User"
            self.latest_auth_time = datetime.now().strftime("%H:%M:%S")

            self.after(0, lambda: self.auth_badge.configure(
                text=f"🟢 ESP Auth: Verified ({self.latest_user_name})",
                fg_color=self.COLORS["success_bg"],
                text_color=self.COLORS["success"]
            ))
        else:
            self.latest_auth_status = False
            self.latest_user_name = "Denied"
            self.latest_auth_time = datetime.now().strftime("%H:%M:%S")

            self.after(0, lambda: self.auth_badge.configure(
                text="🔴 ESP Auth: Access Denied",
                fg_color=self.COLORS["danger_bg"],
                text_color=self.COLORS["danger"]
            ))

        self.after(0, self.update_auth_telemetry_ui)

    # --------------------------------------------------------------------------
    # Tab 4: VMware Tool Settings
    # --------------------------------------------------------------------------
    def setup_settings_tab(self):
        container = ctk.CTkFrame(self.tab_settings, fg_color="transparent")
        container.pack(fill="both", expand=True, padx=20, pady=20)

        card = ctk.CTkFrame(
            container,
            fg_color=self.COLORS["card"],
            border_width=1,
            border_color=self.COLORS["border"],
            corner_radius=16
        )
        card.pack(fill="both", expand=True, padx=10, pady=5)

        ctk.CTkLabel(
            card,
            text="VMware Workstation / Player CLI Tools Path Configuration",
            font=("Segoe UI", 16, "bold"),
            text_color=self.COLORS["text_dark"]
        ).pack(anchor="w", padx=25, pady=(20, 15))

        # vmrun Path
        ctk.CTkLabel(card, text="vmrun.exe Path:", font=("Segoe UI", 12), text_color=self.COLORS["text_muted"]).pack(anchor="w", padx=25, pady=(5, 2))
        vmrun_frame = ctk.CTkFrame(card, fg_color="transparent")
        vmrun_frame.pack(fill="x", padx=25, pady=(0, 15))

        self.entry_vmrun = ctk.CTkEntry(vmrun_frame, font=("Segoe UI", 12))
        self.entry_vmrun.insert(0, self.vmrun_path)
        self.entry_vmrun.pack(side="left", fill="x", expand=True, padx=(0, 10))

        btn_browse_vmrun = ctk.CTkButton(
            vmrun_frame,
            text="Browse...",
            font=("Segoe UI", 11, "bold"),
            width=90,
            command=self.browse_vmrun_path
        )
        btn_browse_vmrun.pack(side="right")

        # vdiskmanager Path
        ctk.CTkLabel(card, text="vmware-vdiskmanager.exe Path:", font=("Segoe UI", 12), text_color=self.COLORS["text_muted"]).pack(anchor="w", padx=25, pady=(5, 2))
        vdisk_frame = ctk.CTkFrame(card, fg_color="transparent")
        vdisk_frame.pack(fill="x", padx=25, pady=(0, 20))

        self.entry_vdisk = ctk.CTkEntry(vdisk_frame, font=("Segoe UI", 12))
        self.entry_vdisk.insert(0, self.vdiskmanager_path)
        self.entry_vdisk.pack(side="left", fill="x", expand=True, padx=(0, 10))

        btn_browse_vdisk = ctk.CTkButton(
            vdisk_frame,
            text="Browse...",
            font=("Segoe UI", 11, "bold"),
            width=90,
            command=self.browse_vdisk_path
        )
        btn_browse_vdisk.pack(side="right")

        ctk.CTkButton(
            card,
            text="Save VMware Tool Paths 💾",
            font=("Segoe UI", 13, "bold"),
            fg_color=self.COLORS["primary"],
            hover_color=self.COLORS["primary_hover"],
            height=40,
            command=self.save_vmware_paths
        ).pack(anchor="w", padx=25, pady=10)

    def browse_vmrun_path(self):
        filepath = filedialog.askopenfilename(filetypes=[("Executable", "vmrun.exe"), ("All Files", "*.*")])
        if filepath:
            self.entry_vmrun.delete(0, "end")
            self.entry_vmrun.insert(0, filepath)

    def browse_vdisk_path(self):
        filepath = filedialog.askopenfilename(filetypes=[("Executable", "vmware-vdiskmanager.exe"), ("All Files", "*.*")])
        if filepath:
            self.entry_vdisk.delete(0, "end")
            self.entry_vdisk.insert(0, filepath)

    def save_vmware_paths(self):
        self.vmrun_path = self.entry_vmrun.get().strip()
        self.vdiskmanager_path = self.entry_vdisk.get().strip()
        self.vmware_badge.configure(
            text=f"⚙️ VMware CLI: {'Found' if os.path.exists(self.vmrun_path) else 'Not Found'}",
            fg_color=self.COLORS["success_bg"] if os.path.exists(self.vmrun_path) else self.COLORS["warning_bg"],
            text_color=self.COLORS["success"] if os.path.exists(self.vmrun_path) else self.COLORS["warning"]
        )
        messagebox.showinfo("Saved", "VMware tool paths updated successfully!")

# ==============================================================================
# Main Entry Point
# ==============================================================================
if __name__ == "__main__":
    app = VMwareOSLoaderApp()
    app.mainloop()
